# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compresses a one-hot vector
#'
#' @param A vector of one-hot values, maximum size 8 elements
#' @return A compressed integer
compress <- function(onehot) {
    .Call(`_XalUtil_compress`, onehot)
}

#' Decompresses an integer to one-hot vector
#'
#' @param An integer (<8 bits wide) to decompress
#' @return A one-hot vector
decompress <- function(compressed, size) {
    .Call(`_XalUtil_decompress`, compressed, size)
}

