# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compresses a one-hot vector
#'
#' @param A vector of one-hot values, maximum size 8 elements
#' @return A compressed integer
compress <- function(onehot) {
    .Call(`_XalUtil_compress`, onehot)
}

#' Decompresses an integer to one-hot vector
#'
#' @param An integer (<8 bits wide) to decompress
#' @return A one-hot vector
decompress <- function(compressed, size) {
    .Call(`_XalUtil_decompress`, compressed, size)
}

#' Compresses an array to one-hot vector
#'
#' @param Input array
#' @param Array row count
#' @param Array column count
#' @return A compressed vector
compress_block <- function(onehot, rows, cols) {
    .Call(`_XalUtil_compress_block`, onehot, rows, cols)
}

#' Decompresses an array to one-hot vector
#'
#' @param Input array
#' @param Array row count
#' @param Array column count
#' @return A decompressed array
decompress_block <- function(onehot, rows, cols) {
    .Call(`_XalUtil_decompress_block`, onehot, rows, cols)
}

